// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm1RvNnXXE0k6kSP45L_6v9I5PAPy5jGw',
    appId: '1:989789228237:android:e7aa20ff5636af949d6d84',
    messagingSenderId: '989789228237',
    projectId: 'ousz-firebase',
    storageBucket: 'ousz-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMhB8W0KmL4cYnNgWvP5zSe-2ybom-ngg',
    appId: '1:989789228237:ios:0e866390820b1eff9d6d84',
    messagingSenderId: '989789228237',
    projectId: 'ousz-firebase',
    storageBucket: 'ousz-firebase.appspot.com',
    iosClientId: '989789228237-ee5urqcqrbl45crte3ro5863sgpckrh7.apps.googleusercontent.com',
    iosBundleId: 'n',
  );
}
